### ISSUE TITLE
upsert of new row with check constraints fails

### ISSUE THREAD

**Issue by cldellow** [simonw/sqlite-utils#514] opened 2022-11-26 16:12 UTC
(I originally opened this in https://github.com/simonw/datasette-insert/issues/20, but I see that that library depends on sqlite-utils)

In the case of a new row, upsert first adds the row, specifying only its pkeys: https://github.com/simonw/sqlite-utils/blob/965ca0d5f5bffe06cc02cd7741344d1ddddf9d56/sqlite_utils/db.py#L2783-L2787

This means that a table with NON NULL (or other constraint) columns that aren't part of the pkey can't have new rows upserted.

**Comment by simonw** [comment] 2023-05-08 21:27
Dupe of:
- #538

**Comment by simonw** [comment] 2023-05-08 21:44
OK, this fails silently:
```python
import sqlite_utils
db = sqlite_utils.Database(memory=True)
db.execute('''CREATE TABLE employees (
    id INTEGER PRIMARY KEY,
    name TEXT,
    age INTEGER,
    salary REAL,
    CHECK (salary is not null and salary > 0)
);''')
db["employees"].upsert({"id": 1, "name": "Bob"}, pk="id")
list(db["employees"].rows)
````
It outputs:
```python
[]
```

**Comment by simonw** [comment] 2023-05-08 21:50
Applying the fix from the PR here doesn't fix the above problem either:
- https://github.com/simonw/sqlite-utils/pull/515

So it looks like these kinds of `check` constraints currently aren't compatible with how `upsert()` works.

**Comment by simonw** [comment] 2023-05-08 21:50
Seeing as `sqlite-utils` doesn't currently provide mechanisms for adding `check` constraints like this I'm going to leave this - I'm happy with the fix I put in for the `not null` constraints.

**Closed by simonw** 2023-05-08 21:50 UTC
