### ISSUE TITLE
Tutorial command no longer works

### ISSUE THREAD

**Issue by petey284** [simonw/sqlite-utils#82] opened 2020-02-03 16:36 UTC
Issue with command on [tutorial](https://simonwillison.net/2019/Feb/25/sqlite-utils/) on Simon's site.

The following command no longer works, and breaks with the previous too many variables error: #50

``` cmd
> curl "https://data.nasa.gov/resource/y77d-th95.json" | \
    sqlite-utils insert meteorites.db meteorites - --pk=id
```

Output:
``` cmd
Traceback (most recent call last):
  File "continuum\miniconda3\envs\main\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "continuum\miniconda3\envs\main\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "Continuum\miniconda3\envs\main\Scripts\sqlite-utils.exe\__main__.py", line 9, in <module>
  File "continuum\miniconda3\envs\main\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "continuum\miniconda3\envs\main\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "continuum\miniconda3\envs\main\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "continuum\miniconda3\envs\main\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "continuum\miniconda3\envs\main\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "continuum\miniconda3\envs\main\lib\site-packages\sqlite_utils\cli.py", line 434, in insert
    default=default,
  File "continuum\miniconda3\envs\main\lib\site-packages\sqlite_utils\cli.py", line 384, in insert_upsert_implementation
    docs, pk=pk, batch_size=batch_size, alter=alter, **extra_kwargs
  File "continuum\miniconda3\envs\main\lib\site-packages\sqlite_utils\db.py", line 1081, in insert_all
    result = self.db.conn.execute(query, params)
sqlite3.OperationalError: too many SQL variables
```

My thought is that maybe the dataset grew over the last few years and so didn't run into this issue before.

No error when I reduce the count of entries to 83. Once the number of entries hits 84 the command fails.

// This passes
``` cmd
type meteorite_83.txt | sqlite-utils insert meteorites.db meteorites - --pk=id
```

// But this fails
``` cmd
type meteorite_84.txt | sqlite-utils insert meteorites.db meteorites - --pk=id
```

A potential fix might be to chunk the incoming data? I can work on a PR if pointed in right direction.

**Comment by simonw** [comment] 2020-02-03 22:32
This should work - the data should be chunked automatically. It looks like this is a bug.

**Comment by simonw** [comment] 2020-02-03 22:35
I can't replicate this problem:
```
/tmp $ sqlite-utils --version
sqlite-utils, version 2.2
/tmp $ curl "https://data.nasa.gov/resource/y77d-th95.json" |     sqlite-utils insert meteorites.db meteorites - --pk=id
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  240k    0  240k    0     0   185k      0 --:--:--  0:00:01 --:--:--  185k
```
Could you run `sqlite-utils --version` and tell me what you get?

**Comment by petey284** [comment] 2020-02-03 23:21
![image](https://user-images.githubusercontent.com/10350886/73699444-d088bf80-46b1-11ea-87c6-11031938b2da.png)

I get version 2.2

I need to continue triaging, since trying again yields a different error.

**Comment by simonw** [comment] 2020-02-27 04:16
Closing as can't reproduce.

**Closed by simonw** 2020-02-27 04:16 UTC
Labels: bug
